services:
 clicker1:
  container_name: clicker1
  build:
      context: .
      dockerfile: Dockerfile
  depends_on:
   - clicker-db
  env_file: ./.env
  networks:
   - clicker
  volumes:
   - ../log/bot.log:/application/bot.log

 clicker-db:
  image: postgres:13-alpine
  env_file: ./.env
  restart: unless-stopped
  tty: true
  networks:
   - clicker
  ports:
   - "25432:5432"
  volumes:
   - /mnt/clicker-db:/var/lib/postgresql/data
   - /tmp/dump:/tmp/dump

networks:
  clicker:
