services:
 clicker1:
  container_name: clicker1
  build:
      context: .
      dockerfile: Dockerfile
  depends_on:
   - clicker-db
  env_file: ./.env
  networks:
   - clicker

 clicker-db:
  image: postgres:13-alpine
  env_file: ./.env
  restart: unless-stopped
  tty: true
  networks:
   - clicker
  ports:
   - "25432:5432"
  volumes:
   - /mnt/clicker-db:/var/lib/postgresql/data
   - /tmp/dump:/tmp/dump

#
# clicker2:
#  container_name: clicker2
#  build:
#      context: .
#      dockerfile: Dockerfile
#  env_file: ./.env
#  networks:
#   - clicker
#
# clicker3:
#  container_name: clicker3
#  build:
#   context: .
#   dockerfile: Dockerfile
#  env_file: ./.env
#  networks:
#   - clicker
#
# clicker4:
#  container_name: clicker4
#  build:
#   context: .
#   dockerfile: Dockerfile
#  env_file: ./.env
#  networks:
#   - clicker
#
# clicker5:
#  container_name: clicker5
#  build:
#   context: .
#   dockerfile: Dockerfile
#  env_file: ./.env
#  networks:
#   - clicker

networks:
  clicker:
